# -*- coding: utf-8 -*-
# vim: ft=yaml
---
include:
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Rules.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Runners/apps.education-docker.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Lint/Commitlint.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Release/Semantic-release.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Docker.yaml

variables:
  # `ci-tools` default branch is `stable`
  STABLE_BRANCH: master
  IMAGE_NAME: laboite-blog_api

stages:
  - initial-checks
  - test
  - build
  - release

# Common setup for all meteor based jobs
.nodejs:
  extends: .not-on-stable
  image: hub.eole.education/proxyhub/library/node:14.16.1-alpine
  cache:
    key:
      files:
        # Generate new cache when one of the file changes
        - package.json
        - package-lock.json
    paths:
      - dist/
      - node_modules/
    # Only use the cache created by `yarn:install` and `yarn:build` jobs
    policy: pull


###############################################################################
# `initial-checks` stage: `commitlint`, `yarn:build`
###############################################################################
commitlint:
  stage: initial-checks

# Verify that the dependencies can be installed and cache dependencies
yarn:build:
  stage: initial-checks
  extends: .nodejs
  cache:
    policy: pull-push
  script:
    - yarn install
    - yarn run clean
    - yarn run build


###############################################################################
# `test` stage: `prettier`, `eslint`, `js-test`
###############################################################################
prettier:
  stage: test
  extends: .nodejs
  allow_failure: true
  script:
    - yarn run prettier:check

eslint:
  stage: test
  extends: .nodejs
  allow_failure: true
  script:
    - yarn run eslint

js-test:
  stage: test
  extends: .nodejs
  allow_failure: true
  script:
    - yarn run test


###############################################################################
# `build` stage: `build-docker`
###############################################################################
# Build on release tag and every branches except for `$STABLE_BRANCH`
# used only to create the release tag.
#
# The ordering is important:
# 1. exclude schedules and drafts
# 2. include `on-release-tag` which must match before `not-on-semantic-release-commit`
# 3. we exclude stable which just produce the release tag
# 4. we exclude `semantic-release` commits like when merging `release` on `dev`
# 5. run on every branches
build-docker:
  extends: .build-docker-image
  rules:
    - !reference [.rules-map, not-on-schedule]
    - !reference [.rules-map, not-on-draft]
    - !reference [.rules-map, on-release-tag]
    - !reference [.rules-map, not-on-stable]
    - !reference [.rules-map, not-on-semantic-release-commit]
    - !reference [.rules-map, on-branch]


###############################################################################
# `release` stage: `semantic-release`, `merge-to-dev`, `tag`
###############################################################################
# Avoid regression and update `version` of package*.json in `$DEV_BRANCH`
merge-to-dev:
  stage: release
  extends:
    - .on-release-tag
  image: 'hub.eole.education/eole/commitlint:latest'
  script:
    # Add `upstream` remote to get access to `upstream/dev`
    # Use `${GITLAB_TOKEN}` for write permission
    - "git remote show upstream 2> /dev/null || git remote add upstream ${CI_REPOSITORY_URL/${CI_JOB_TOKEN}/${GITLAB_TOKEN}}"
    - 'git fetch --all'
    - 'git checkout -b ${DEV_BRANCH} upstream/${DEV_BRANCH}'
    - 'git merge --no-edit ${CI_COMMIT_TAG}'
    - 'git push upstream ${DEV_BRANCH}'
    # Remove `upstream` to avoid caching `CI_JOB_TOKEN`
    - "git remote remove upstream"

## tag contribution branches with a more stable name than `git-${CI_COMMIT_SHORT_SHA}`
tag contrib branch:
  extends:
    - .tag-docker-image
    - .on-branches
  variables:
    # `feature/foo-bar_quux` → `feature-foo-bar-quux`
    IMAGE_TAG: $CI_COMMIT_REF_SLUG

## dev images
tag dev:
  extends:
    - .tag-docker-image
    - .on-dev
  variables:
    IMAGE_TAG: dev

## testing images
tag testing:
  extends:
    - .tag-docker-image
    - .on-testing
  variables:
    IMAGE_TAG: testing

## stable images
tag release:
  extends: .tag-docker-image

tag major:
  extends: .tag-docker-image
  before_script:
    - export RELEASE_PREFIX=${RELEASE_PREFIX:-release/}
    - export RELEASE=${CI_COMMIT_TAG#${RELEASE_PREFIX}}
    - export IMAGE_TAG=${RELEASE%%.*}

tag minor:
  extends:
    - .tag-docker-image
  before_script:
    - export RELEASE_PREFIX=${RELEASE_PREFIX:-release/}
    - export RELEASE=${CI_COMMIT_TAG#${RELEASE_PREFIX}}
    - export IMAGE_TAG=${RELEASE%.${RELEASE##*.}}

tag stable:
  extends: .tag-docker-image
  variables:
    IMAGE_TAG: stable

tag latest:
  extends: .tag-docker-image
  variables:
    IMAGE_TAG: latest
