# -*- coding: utf-8 -*-
# vim: ft=yaml
---
include:
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Rules.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Runners/apps.education-docker.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Lint/Commitlint.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Release/Semantic-release.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Docker.yaml

variables:
  # `ci-tools` default branch is `stable`
  STABLE_BRANCH: master
  IMAGE_NAME: laboite-blog_api

stages:
  - initial-checks
  - test
  - build
  - release

# Common setup for all meteor based jobs
.nodejs:
  extends: .not-on-stable
  image: hub.eole.education/proxyhub/library/node:14.16.1-alpine
  cache:
    key:
      files:
        # Generate new cache when one of the file changes
        - package.json
        - package-lock.json
    paths:
      - dist/
      - node_modules/
    # Only use the cache created by `yarn:install` and `yarn:build` jobs
    policy: pull


###############################################################################
# `initial-checks` stage: `commitlint`, `yarn:build`
###############################################################################
commitlint:
  stage: initial-checks

# Verify that the dependencies can be installed and cache dependencies
yarn:build:
  stage: initial-checks
  extends: .nodejs
  cache:
    policy: pull-push
  script:
    - yarn install
    - yarn run clean
    - yarn run build


###############################################################################
# `test` stage: `prettier`, `eslint`, `js-test`
###############################################################################
prettier:
  stage: test
  extends: .nodejs
  allow_failure: true
  script:
    - yarn run prettier:check

eslint:
  stage: test
  extends: .nodejs
  allow_failure: true
  script:
    - yarn run eslint

js-test:
  stage: test
  extends: .nodejs
  allow_failure: true
  script:
    - yarn run test


###############################################################################
# `build` stage: `build-docker`
###############################################################################
# Build on release tag and every branches except for `$STABLE_BRANCH`
# used only to create the release tag.
#
# The ordering is important:
# 1. exclude schedules and drafts
# 2. include `on-release-tag` which must match before `not-on-semantic-release-commit`
# 3. we exclude stable which just produce the release tag
# 4. we exclude `semantic-release` commits like when merging `release` on `dev`
# 5. run on every branches
build-docker:
  extends: .build-docker-image
  rules:
    - !reference [.rules-map, not-on-schedule]
    - !reference [.rules-map, not-on-draft]
    - !reference [.rules-map, on-release-tag]
    - !reference [.rules-map, not-on-stable]
    - !reference [.rules-map, not-on-semantic-release-commit]
    - !reference [.rules-map, on-branch]


###############################################################################
# `release` stage: `semantic-release`
###############################################################################
